// Code generated by protoc-gen-actionqueue. DO NOT EDIT.
// source: v1/example.proto

package v1

import (
	"fmt"
	actionqueue "github.com/jirwin/protoc-gen-actionqueue/pkg/actionqueue"
	workflow "go.temporal.io/sdk/workflow"
	proto "google.golang.org/protobuf/proto"
)

const (
	UserSyncQueueName   = "user-sync-queue"
	UserSyncQueueSignal = "signal:start:user-sync-queue"
)

// UserSyncActionWorkflowID returns the workflow ID for a UserSyncAction action.
func UserSyncActionWorkflowID(action proto.Message) string {
	a := action.(*UserSyncAction)
	return fmt.Sprintf("user-sync-queue:%s:%s", a.GetTenantId(), a.GetUserId())
}

// UserSyncActionTenantID extracts the tenant ID from a UserSyncAction action.
func UserSyncActionTenantID(action proto.Message) string {
	return action.(*UserSyncAction).GetTenantId()
}

// UserSyncQueueDefinition creates an actionqueue.Definition for the user-sync-queue queue.
func UserSyncQueueDefinition(activityMain any, workflowFunc any, activityOptions func() workflow.ActivityOptions) *actionqueue.Definition {
	return &actionqueue.Definition{
		ActionProto:     &UserSyncAction{},
		ActivityMain:    activityMain,
		ActivityOptions: activityOptions,
		Name:            UserSyncQueueName,
		Signal:          UserSyncQueueSignal,
		TenantIDFunc:    UserSyncActionTenantID,
		WorkflowFunc:    workflowFunc,
		WorkflowIDFunc:  UserSyncActionWorkflowID,
	}
}

func init() {
	// Register user-sync-queue queue definition placeholder
	_ = UserSyncQueueName
}
