// Code generated by protoc-gen-actionqueue. DO NOT EDIT.
// source: v1/example.proto

package v1

import (
	"fmt"
	actionqueue "github.com/jirwin/protoc-gen-actionqueue/pkg/actionqueue"
	proto "google.golang.org/protobuf/proto"
)

const (
	UserSyncQueueName   = "user-sync-queue"
	UserSyncQueueSignal = "signal:start:user-sync-queue"
)

// UserSyncActionWorkflowID returns the workflow ID for a UserSyncAction action.
func UserSyncActionWorkflowID(action proto.Message) string {
	a := action.(*UserSyncAction)
	return fmt.Sprintf("user-sync-queue:%s:%s", a.GetTenantId(), a.GetUserId())
}

// UserSyncActionTenantID extracts the tenant ID from a UserSyncAction action.
func UserSyncActionTenantID(action proto.Message) string {
	return action.(*UserSyncAction).GetTenantId()
}

// UserSyncActionEntityIDs extracts the non-tenant entity IDs from a UserSyncAction action.
func UserSyncActionEntityIDs(action proto.Message) []string {
	a := action.(*UserSyncAction)
	return []string{a.GetUserId()}
}

// UserSyncQueueWorkflowIDFromArgs constructs a workflow ID from individual arguments.
func UserSyncQueueWorkflowIDFromArgs(tenantID string, entityIDs []string) string {
	return fmt.Sprintf("user-sync-queue:%s:%s", tenantID, entityIDs[0])
}

// UserSyncQueueDefinition creates an actionqueue.Definition for the user-sync-queue queue.
// Runtime fields (ActivityMain, WorkflowFunc, ActivityOptions) are set when a driver is bound.
func UserSyncQueueDefinition() *actionqueue.Definition {
	return &actionqueue.Definition{
		ActionProto:        &UserSyncAction{},
		EntityIDsFunc:      UserSyncActionEntityIDs,
		Name:               UserSyncQueueName,
		Signal:             UserSyncQueueSignal,
		TenantIDFunc:       UserSyncActionTenantID,
		WorkflowIDFromArgs: UserSyncQueueWorkflowIDFromArgs,
		WorkflowIDFunc:     UserSyncActionWorkflowID,
	}
}

func init() {
	actionqueue.Register(UserSyncQueueDefinition())
}
