// Code generated by protoc-gen-actionqueue. DO NOT EDIT.
// source: v1/example.proto

package v1

import (
	"fmt"
	actionqueue "github.com/jirwin/protoc-gen-actionqueue/pkg/actionqueue"
	ksuid "github.com/segmentio/ksuid"
	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	BookQueueName                                         = "book-queue"
	BookQueueSignal                                       = "signal:start:book-queue"
	BookActionEventKeyCheckout   protoreflect.FieldNumber = 10
	BookActionEventKeyReturnBook protoreflect.FieldNumber = 11
)

// BookActionWorkflowID returns the workflow ID for a BookAction action.
func BookActionWorkflowID(action proto.Message) string {
	a := action.(*BookAction)
	return fmt.Sprintf("action-queue-book-queue:%s:%s", a.GetTenantId(), a.GetBookId())
}

// BookActionTenantID extracts the tenant ID from a BookAction action.
func BookActionTenantID(action proto.Message) string {
	return action.(*BookAction).GetTenantId()
}

// BookActionEntityIDs extracts the non-tenant entity IDs from a BookAction action.
func BookActionEntityIDs(action proto.Message) []string {
	a := action.(*BookAction)
	return []string{a.GetBookId()}
}

// BookQueueWorkflowIDFromArgs constructs a workflow ID from individual arguments.
func BookQueueWorkflowIDFromArgs(tenantID string, entityIDs []string) string {
	return fmt.Sprintf("action-queue-book-queue:%s:%s", tenantID, entityIDs[0])
}

// BookActionPKTemplate creates a PK template for listing actions.
func BookActionPKTemplate(tenantID string, entityIDs []string) *BookAction {
	return &BookAction{
		BookId:   entityIDs[0],
		TenantId: tenantID,
	}
}

// BookActionNextCheckout creates a new BookAction with the Checkout event, copying PK fields and generating a fresh ID.
func BookActionNextCheckout(current *BookAction, deadline *timestamppb.Timestamp, event *CheckoutEvent) *BookAction {
	if deadline == nil {
		deadline = timestamppb.Now()
	}
	return &BookAction{
		BookId:   current.GetBookId(),
		Deadline: deadline,
		Event:    &BookAction_Checkout{Checkout: event},
		Id:       ksuid.New().String(),
		TenantId: current.GetTenantId(),
	}
}

// BookActionNextReturnBook creates a new BookAction with the ReturnBook event, copying PK fields and generating a fresh ID.
func BookActionNextReturnBook(current *BookAction, deadline *timestamppb.Timestamp, event *ReturnEvent) *BookAction {
	if deadline == nil {
		deadline = timestamppb.Now()
	}
	return &BookAction{
		BookId:   current.GetBookId(),
		Deadline: deadline,
		Event:    &BookAction_ReturnBook{ReturnBook: event},
		Id:       ksuid.New().String(),
		TenantId: current.GetTenantId(),
	}
}

// BookQueueDefinition creates an actionqueue.Definition for the book-queue queue.
// Runtime fields (ActivityMain, WorkflowFunc, ActivityOptions) are set when a driver is bound.
func BookQueueDefinition() *actionqueue.Definition {
	return &actionqueue.Definition{
		ActionProto:        &BookAction{},
		EntityIDsFunc:      BookActionEntityIDs,
		Name:               BookQueueName,
		Signal:             BookQueueSignal,
		TenantIDFunc:       BookActionTenantID,
		WorkflowIDFromArgs: BookQueueWorkflowIDFromArgs,
		WorkflowIDFunc:     BookActionWorkflowID,
	}
}

func init() {
	actionqueue.Register(BookQueueDefinition())
}
