// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/example.proto

package v1

import (
	_ "github.com/jirwin/protoc-gen-actionqueue/actionqueue/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckoutEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BorrowerId    string                 `protobuf:"bytes,1,opt,name=borrower_id,json=borrowerId,proto3" json:"borrower_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutEvent) Reset() {
	*x = CheckoutEvent{}
	mi := &file_v1_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutEvent) ProtoMessage() {}

func (x *CheckoutEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutEvent.ProtoReflect.Descriptor instead.
func (*CheckoutEvent) Descriptor() ([]byte, []int) {
	return file_v1_example_proto_rawDescGZIP(), []int{0}
}

func (x *CheckoutEvent) GetBorrowerId() string {
	if x != nil {
		return x.BorrowerId
	}
	return ""
}

type ReturnEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     string                 `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnEvent) Reset() {
	*x = ReturnEvent{}
	mi := &file_v1_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnEvent) ProtoMessage() {}

func (x *ReturnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnEvent.ProtoReflect.Descriptor instead.
func (*ReturnEvent) Descriptor() ([]byte, []int) {
	return file_v1_example_proto_rawDescGZIP(), []int{1}
}

func (x *ReturnEvent) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type BookAction struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Deadline *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=deadline,proto3" json:"deadline,omitempty"`
	TenantId string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BookId   string                 `protobuf:"bytes,3,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Id       string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*BookAction_Checkout
	//	*BookAction_ReturnBook
	Event         isBookAction_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookAction) Reset() {
	*x = BookAction{}
	mi := &file_v1_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookAction) ProtoMessage() {}

func (x *BookAction) ProtoReflect() protoreflect.Message {
	mi := &file_v1_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookAction.ProtoReflect.Descriptor instead.
func (*BookAction) Descriptor() ([]byte, []int) {
	return file_v1_example_proto_rawDescGZIP(), []int{2}
}

func (x *BookAction) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *BookAction) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BookAction) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *BookAction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookAction) GetEvent() isBookAction_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *BookAction) GetCheckout() *CheckoutEvent {
	if x != nil {
		if x, ok := x.Event.(*BookAction_Checkout); ok {
			return x.Checkout
		}
	}
	return nil
}

func (x *BookAction) GetReturnBook() *ReturnEvent {
	if x != nil {
		if x, ok := x.Event.(*BookAction_ReturnBook); ok {
			return x.ReturnBook
		}
	}
	return nil
}

type isBookAction_Event interface {
	isBookAction_Event()
}

type BookAction_Checkout struct {
	Checkout *CheckoutEvent `protobuf:"bytes,10,opt,name=checkout,proto3,oneof"`
}

type BookAction_ReturnBook struct {
	ReturnBook *ReturnEvent `protobuf:"bytes,11,opt,name=return_book,json=returnBook,proto3,oneof"`
}

func (*BookAction_Checkout) isBookAction_Event() {}

func (*BookAction_ReturnBook) isBookAction_Event() {}

var File_v1_example_proto protoreflect.FileDescriptor

const file_v1_example_proto_rawDesc = "" +
	"\n" +
	"\x10v1/example.proto\x12\n" +
	"example.v1\x1a\x1cactionqueue/v1/options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\rCheckoutEvent\x12\x1f\n" +
	"\vborrower_id\x18\x01 \x01(\tR\n" +
	"borrowerId\"+\n" +
	"\vReturnEvent\x12\x1c\n" +
	"\tcondition\x18\x01 \x01(\tR\tcondition\"\xd2\x02\n" +
	"\n" +
	"BookAction\x126\n" +
	"\bdeadline\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\abook_id\x18\x03 \x01(\tR\x06bookId\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x127\n" +
	"\bcheckout\x18\n" +
	" \x01(\v2\x19.example.v1.CheckoutEventH\x00R\bcheckout\x12:\n" +
	"\vreturn_book\x18\v \x01(\v2\x17.example.v1.ReturnEventH\x00R\n" +
	"returnBook:H\xe2\xbb\x03D\n" +
	"\n" +
	"book-queue\x12\x17signal:start:book-queue\x1a\ttenant_id\x1a\abook_id\"\ttenant_idB\a\n" +
	"\x05eventB5Z3github.com/jirwin/protoc-gen-actionqueue/example/v1b\x06proto3"

var (
	file_v1_example_proto_rawDescOnce sync.Once
	file_v1_example_proto_rawDescData []byte
)

func file_v1_example_proto_rawDescGZIP() []byte {
	file_v1_example_proto_rawDescOnce.Do(func() {
		file_v1_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_example_proto_rawDesc), len(file_v1_example_proto_rawDesc)))
	})
	return file_v1_example_proto_rawDescData
}

var file_v1_example_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_example_proto_goTypes = []any{
	(*CheckoutEvent)(nil),         // 0: example.v1.CheckoutEvent
	(*ReturnEvent)(nil),           // 1: example.v1.ReturnEvent
	(*BookAction)(nil),            // 2: example.v1.BookAction
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_v1_example_proto_depIdxs = []int32{
	3, // 0: example.v1.BookAction.deadline:type_name -> google.protobuf.Timestamp
	0, // 1: example.v1.BookAction.checkout:type_name -> example.v1.CheckoutEvent
	1, // 2: example.v1.BookAction.return_book:type_name -> example.v1.ReturnEvent
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_example_proto_init() }
func file_v1_example_proto_init() {
	if File_v1_example_proto != nil {
		return
	}
	file_v1_example_proto_msgTypes[2].OneofWrappers = []any{
		(*BookAction_Checkout)(nil),
		(*BookAction_ReturnBook)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_example_proto_rawDesc), len(file_v1_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_example_proto_goTypes,
		DependencyIndexes: file_v1_example_proto_depIdxs,
		MessageInfos:      file_v1_example_proto_msgTypes,
	}.Build()
	File_v1_example_proto = out.File
	file_v1_example_proto_goTypes = nil
	file_v1_example_proto_depIdxs = nil
}
