// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/example.proto

package v1

import (
	_ "github.com/jirwin/protoc-gen-actionqueue/actionqueue/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserSyncAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SyncReason    string                 `protobuf:"bytes,3,opt,name=sync_reason,json=syncReason,proto3" json:"sync_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSyncAction) Reset() {
	*x = UserSyncAction{}
	mi := &file_v1_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSyncAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSyncAction) ProtoMessage() {}

func (x *UserSyncAction) ProtoReflect() protoreflect.Message {
	mi := &file_v1_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSyncAction.ProtoReflect.Descriptor instead.
func (*UserSyncAction) Descriptor() ([]byte, []int) {
	return file_v1_example_proto_rawDescGZIP(), []int{0}
}

func (x *UserSyncAction) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UserSyncAction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSyncAction) GetSyncReason() string {
	if x != nil {
		return x.SyncReason
	}
	return ""
}

var File_v1_example_proto protoreflect.FileDescriptor

const file_v1_example_proto_rawDesc = "" +
	"\n" +
	"\x10v1/example.proto\x12\n" +
	"example.v1\x1a\x1cactionqueue/v1/options.proto\"\xbb\x01\n" +
	"\x0eUserSyncAction\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vsync_reason\x18\x03 \x01(\tR\n" +
	"syncReason:R\xe2\xbb\x03N\n" +
	"\x0fuser-sync-queue\x12\x1csignal:start:user-sync-queue\x1a\ttenant_id\x1a\auser_id\"\ttenant_idB5Z3github.com/jirwin/protoc-gen-actionqueue/example/v1b\x06proto3"

var (
	file_v1_example_proto_rawDescOnce sync.Once
	file_v1_example_proto_rawDescData []byte
)

func file_v1_example_proto_rawDescGZIP() []byte {
	file_v1_example_proto_rawDescOnce.Do(func() {
		file_v1_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_example_proto_rawDesc), len(file_v1_example_proto_rawDesc)))
	})
	return file_v1_example_proto_rawDescData
}

var file_v1_example_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_example_proto_goTypes = []any{
	(*UserSyncAction)(nil), // 0: example.v1.UserSyncAction
}
var file_v1_example_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_example_proto_init() }
func file_v1_example_proto_init() {
	if File_v1_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_example_proto_rawDesc), len(file_v1_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_example_proto_goTypes,
		DependencyIndexes: file_v1_example_proto_depIdxs,
		MessageInfos:      file_v1_example_proto_msgTypes,
	}.Build()
	File_v1_example_proto = out.File
	file_v1_example_proto_goTypes = nil
	file_v1_example_proto_depIdxs = nil
}
