package pgactionqueue

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/dave/jennifer/jen"
	pgs "github.com/lyft/protoc-gen-star/v2"
	pgsgo "github.com/lyft/protoc-gen-star/v2/lang/go"
	"google.golang.org/protobuf/proto"

	actionqueuepb "github.com/jirwin/protoc-gen-actionqueue/actionqueue/v1"
)

const (
	moduleName = "actionqueue"
	version    = "0.1.0"
)

type Module struct {
	*pgs.ModuleBase
	ctx pgsgo.Context
}

var _ pgs.Module = (*Module)(nil)

func New() pgs.Module {
	return &Module{ModuleBase: &pgs.ModuleBase{}}
}

func (m *Module) InitContext(ctx pgs.BuildContext) {
	m.ModuleBase.InitContext(ctx)
	m.ctx = pgsgo.InitContext(ctx.Parameters())
}

func (m *Module) Name() string {
	return moduleName
}

func (m *Module) Execute(targets map[string]pgs.File, pkgs map[string]pgs.Package) []pgs.Artifact {
	// Track all queue names globally to ensure uniqueness
	queueNames := make(map[string]string) // queue name -> proto full name

	for _, f := range targets {
		m.generateFile(f, queueNames)
	}

	return m.Artifacts()
}

func (m *Module) generateFile(f pgs.File, queueNames map[string]string) {
	if len(f.Messages()) == 0 {
		return
	}

	// Collect all messages with action annotations in this file
	var messagesToGenerate []pgs.Message

	for _, msg := range f.AllMessages() {
		if m.shouldGenerate(msg, queueNames) {
			messagesToGenerate = append(messagesToGenerate, msg)
		}
	}

	if len(messagesToGenerate) == 0 {
		return
	}

	// Generate .pb.actionqueue.go file
	// OutputPath returns something like "foo.pb.go", so we strip the .pb.go and add our extension
	basePath := m.ctx.OutputPath(f).String()
	basePath = strings.TrimSuffix(basePath, ".pb.go")
	name := pgs.FilePath(basePath + ".pb.actionqueue.go")

	// Create jennifer file
	importPath := m.ctx.ImportPath(f).String()
	pkgName := m.ctx.PackageName(f).String()
	code := jen.NewFilePathName(importPath, pkgName)
	code.HeaderComment("Code generated by protoc-gen-actionqueue. DO NOT EDIT.")
	code.HeaderComment(fmt.Sprintf("source: %s", f.Name()))

	// Generate code for each message
	for _, msg := range messagesToGenerate {
		m.generateMessage(code, msg)
	}

	// Generate init() function to register all types
	m.generateInit(code, messagesToGenerate)

	// Render to bytes buffer
	var buf bytes.Buffer
	if err := code.Render(&buf); err != nil {
		m.Failf("failed to render code for %s: %v", f.Name(), err)
		return
	}
	m.AddGeneratorFile(name.String(), buf.String())
}

func (m *Module) shouldGenerate(msg pgs.Message, queueNames map[string]string) bool {
	// Check if message has actionqueue.v1.action annotation
	opts := msg.Descriptor().GetOptions()
	if opts == nil {
		return false
	}

	if !proto.HasExtension(opts, actionqueuepb.E_Action) {
		return false
	}

	ext := proto.GetExtension(opts, actionqueuepb.E_Action).(*actionqueuepb.MessageOptions)
	if ext == nil {
		return false
	}

	// Validate name
	if ext.Name == "" {
		m.Failf("message %s has actionqueue.v1.action but no name set", msg.FullyQualifiedName())
		return false
	}

	// Validate signal
	if ext.Signal == "" {
		m.Failf("message %s has actionqueue.v1.action but no signal set", msg.FullyQualifiedName())
		return false
	}

	// Check for duplicate queue names
	if existing, ok := queueNames[ext.Name]; ok {
		m.Failf("queue name %q is already used by %s (attempted to use for %s)",
			ext.Name, existing, msg.FullyQualifiedName())
		return false
	}

	// Validate workflow_id_fields
	if len(ext.WorkflowIdFields) == 0 {
		m.Failf("message %s has actionqueue.v1.action but workflow_id_fields is empty", msg.FullyQualifiedName())
		return false
	}

	for _, fieldName := range ext.WorkflowIdFields {
		field := m.findField(msg, fieldName)
		if field == nil {
			m.Failf("message %s has workflow_id_fields containing unknown field: %q", msg.FullyQualifiedName(), fieldName)
			return false
		}

		// Check if field is a scalar type
		if field.Type().IsRepeated() {
			m.Failf("message %s has workflow_id_fields containing repeated field: %q", msg.FullyQualifiedName(), fieldName)
			return false
		}

		if field.Type().IsMap() {
			m.Failf("message %s has workflow_id_fields containing map field: %q", msg.FullyQualifiedName(), fieldName)
			return false
		}

		if field.Type().IsEmbed() {
			m.Failf("message %s has workflow_id_fields containing message field: %q", msg.FullyQualifiedName(), fieldName)
			return false
		}
	}

	// Validate tenant_id_field (or default "tenant_id")
	tenantField := ext.TenantIdField
	if tenantField == "" {
		tenantField = "tenant_id"
	}
	if m.findField(msg, tenantField) == nil {
		m.Failf("message %s is missing tenant_id field %q", msg.FullyQualifiedName(), tenantField)
		return false
	}

	// Validate id_field (or default "id")
	idField := ext.IdField
	if idField == "" {
		idField = "id"
	}
	if m.findField(msg, idField) == nil {
		m.Failf("message %s is missing id field %q", msg.FullyQualifiedName(), idField)
		return false
	}

	// Validate that the message has a `oneof event` with message-typed fields
	var hasEventOneof bool
	for _, oo := range msg.OneOfs() {
		if oo.Name().String() == "event" {
			hasEventOneof = true
			for _, field := range oo.Fields() {
				if !field.Type().IsEmbed() {
					m.Failf("message %s oneof event field %q must be a message type, got %s",
						msg.FullyQualifiedName(), field.Name().String(), field.Type().ProtoType().String())
					return false
				}
			}
			break
		}
	}
	if !hasEventOneof {
		m.Failf("message %s must have a `oneof event` field", msg.FullyQualifiedName())
		return false
	}

	queueNames[ext.Name] = msg.FullyQualifiedName()
	return true
}

func (m *Module) generateMessage(code *jen.File, msg pgs.Message) {
	msgName := m.ctx.Name(msg).String()

	// Get action annotation
	opts := msg.Descriptor().GetOptions()
	ext := proto.GetExtension(opts, actionqueuepb.E_Action).(*actionqueuepb.MessageOptions)
	queueName := ext.Name
	signal := ext.Signal
	workflowIDFields := ext.WorkflowIdFields
	tenantField := ext.TenantIdField
	if tenantField == "" {
		tenantField = "tenant_id"
	}

	// Convert queue name to PascalCase for function/const names
	// e.g., "my-entity-queue" -> "MyEntityQueue"
	pascalName := toPascalCase(queueName)

	// Compute entity ID fields (workflow_id_fields excluding tenant_id_field)
	var entityIDFields []string
	for _, f := range workflowIDFields {
		if f != tenantField {
			entityIDFields = append(entityIDFields, f)
		}
	}

	// Find the oneof event fields for EventKey generation
	var eventOneofFields []pgs.Field
	for _, oo := range msg.OneOfs() {
		if oo.Name().String() == "event" {
			eventOneofFields = oo.Fields()
			break
		}
	}

	// Generate constants: name, signal, and EventKey per oneof field
	constDefs := []jen.Code{
		jen.Id(pascalName + "Name").Op("=").Lit(queueName),
		jen.Id(pascalName + "Signal").Op("=").Lit(signal),
	}
	for _, field := range eventOneofFields {
		goFieldName := field.Name().UpperCamelCase().String()
		fieldNumber := field.Descriptor().GetNumber()
		constDefs = append(constDefs,
			jen.Id(msgName+"EventKey"+goFieldName).Qual("google.golang.org/protobuf/reflect/protoreflect", "FieldNumber").Op("=").Lit(int(fieldNumber)),
		)
	}
	code.Const().Defs(constDefs...)
	code.Line()

	// Generate WorkflowID function
	code.Comment(fmt.Sprintf("%sWorkflowID returns the workflow ID for a %s action.", msgName, msgName))

	// Build the format string and arguments for Sprintf
	sprintfArgs := []jen.Code{
		jen.Lit(queueName + ":" + strings.Repeat("%s:", len(workflowIDFields)-1) + "%s"),
	}
	sprintfArgs = append(sprintfArgs, m.generateWorkflowIDArgs(msg, workflowIDFields)...)

	code.Func().Id(msgName + "WorkflowID").Params(
		jen.Id("action").Qual("google.golang.org/protobuf/proto", "Message"),
	).String().Block(
		jen.Id("a").Op(":=").Id("action").Assert(jen.Op("*").Id(msgName)),
		jen.Return(jen.Qual("fmt", "Sprintf").Call(sprintfArgs...)),
	)
	code.Line()

	// Generate TenantID function
	code.Comment(fmt.Sprintf("%sTenantID extracts the tenant ID from a %s action.", msgName, msgName))
	code.Func().Id(msgName + "TenantID").Params(
		jen.Id("action").Qual("google.golang.org/protobuf/proto", "Message"),
	).String().Block(
		jen.Return(jen.Id("action").Assert(jen.Op("*").Id(msgName)).Dot("Get"+toPascalCase(tenantField)).Call()),
	)
	code.Line()

	// Generate EntityIDs function (non-tenant workflow ID fields)
	code.Comment(fmt.Sprintf("%sEntityIDs extracts the non-tenant entity IDs from a %s action.", msgName, msgName))
	var entityIDStmts []jen.Code
	var entityIDElems []jen.Code
	if len(entityIDFields) > 0 {
		entityIDStmts = append(entityIDStmts, jen.Id("a").Op(":=").Id("action").Assert(jen.Op("*").Id(msgName)))
		for _, fieldName := range entityIDFields {
			field := m.findField(msg, fieldName)
			goFieldName := field.Name().UpperCamelCase().String()
			entityIDElems = append(entityIDElems, jen.Id("a").Dot("Get"+goFieldName).Call())
		}
	}
	entityIDStmts = append(entityIDStmts, jen.Return(jen.Index().String().Values(entityIDElems...)))

	code.Func().Id(msgName + "EntityIDs").Params(
		jen.Id("action").Qual("google.golang.org/protobuf/proto", "Message"),
	).Index().String().Block(entityIDStmts...)
	code.Line()

	// Generate WorkflowIDFromArgs function
	// Constructs workflow ID from tenantID + entityIDs without needing the full proto
	code.Comment(fmt.Sprintf("%sWorkflowIDFromArgs constructs a workflow ID from individual arguments.", pascalName))
	var fromArgsSprintfArgs []jen.Code
	fromArgsFmt := queueName + ":"
	argIndex := 0
	for i, fieldName := range workflowIDFields {
		if i > 0 {
			fromArgsFmt += ":"
		}
		if fieldName == tenantField {
			fromArgsFmt += "%s"
			fromArgsSprintfArgs = append(fromArgsSprintfArgs, jen.Id("tenantID"))
		} else {
			fromArgsFmt += "%s"
			fromArgsSprintfArgs = append(fromArgsSprintfArgs, jen.Id("entityIDs").Index(jen.Lit(argIndex)))
			argIndex++
		}
	}
	allFromArgsSprintfArgs := []jen.Code{jen.Lit(fromArgsFmt)}
	allFromArgsSprintfArgs = append(allFromArgsSprintfArgs, fromArgsSprintfArgs...)

	code.Func().Id(pascalName + "WorkflowIDFromArgs").Params(
		jen.Id("tenantID").String(),
		jen.Id("entityIDs").Index().String(),
	).String().Block(
		jen.Return(jen.Qual("fmt", "Sprintf").Call(allFromArgsSprintfArgs...)),
	)
	code.Line()

	// Generate PKTemplate function
	// Creates a zero-value action with PK fields set for listing via ScanWithPK/UnrollAll.
	code.Comment(fmt.Sprintf("%sPKTemplate creates a PK template for listing actions.", msgName))
	var pkTemplateFields jen.Dict
	pkTemplateFields = make(jen.Dict)
	argIdx := 0
	for _, fieldName := range workflowIDFields {
		field := m.findField(msg, fieldName)
		goFieldName := field.Name().UpperCamelCase().String()
		if fieldName == tenantField {
			pkTemplateFields[jen.Id(goFieldName)] = jen.Id("tenantID")
		} else {
			pkTemplateFields[jen.Id(goFieldName)] = jen.Id("entityIDs").Index(jen.Lit(argIdx))
			argIdx++
		}
	}
	code.Func().Id(msgName + "PKTemplate").Params(
		jen.Id("tenantID").String(),
		jen.Id("entityIDs").Index().String(),
	).Op("*").Id(msgName).Block(
		jen.Return(jen.Op("&").Id(msgName).Values(pkTemplateFields)),
	)
	code.Line()

	// Generate per-event Next helper functions
	idField := ext.IdField
	if idField == "" {
		idField = "id"
	}
	goIDFieldName := m.findField(msg, idField).Name().UpperCamelCase().String()

	for _, field := range eventOneofFields {
		eventFieldUCC := field.Name().UpperCamelCase().String()
		eventMsgName := m.ctx.Name(field.Type().Embed()).String()

		code.Comment(fmt.Sprintf("%sNext%s creates a new %s with the %s event, copying PK fields and generating a fresh ID.",
			msgName, eventFieldUCC, msgName, eventFieldUCC))

		// Build the struct literal fields
		structFields := make(jen.Dict)
		for _, wfField := range workflowIDFields {
			f := m.findField(msg, wfField)
			goName := f.Name().UpperCamelCase().String()
			structFields[jen.Id(goName)] = jen.Id("current").Dot("Get" + goName).Call()
		}
		structFields[jen.Id(goIDFieldName)] = jen.Qual("github.com/segmentio/ksuid", "New").Call().Dot("String").Call()
		structFields[jen.Id("Deadline")] = jen.Id("deadline")
		structFields[jen.Id("Event")] = jen.Op("&").Id(msgName + "_" + eventFieldUCC).Values(jen.Dict{
			jen.Id(eventFieldUCC): jen.Id("event"),
		})

		code.Func().Id(msgName + "Next" + eventFieldUCC).Params(
			jen.Id("current").Op("*").Id(msgName),
			jen.Id("deadline").Op("*").Qual("google.golang.org/protobuf/types/known/timestamppb", "Timestamp"),
			jen.Id("event").Op("*").Id(eventMsgName),
		).Op("*").Id(msgName).Block(
			jen.Return(jen.Op("&").Id(msgName).Values(structFields)),
		)
		code.Line()
	}

	// Generate zero-arg Definition factory function
	code.Comment(fmt.Sprintf("%sDefinition creates an actionqueue.Definition for the %s queue.", pascalName, queueName))
	code.Comment("Runtime fields (ActivityMain, WorkflowFunc, ActivityOptions) are set when a driver is bound.")
	code.Func().Id(pascalName + "Definition").Params().Op("*").Qual(
		"github.com/jirwin/protoc-gen-actionqueue/pkg/actionqueue", "Definition",
	).Block(
		jen.Return(jen.Op("&").Qual("github.com/jirwin/protoc-gen-actionqueue/pkg/actionqueue", "Definition").Values(jen.Dict{
			jen.Id("Name"):               jen.Id(pascalName + "Name"),
			jen.Id("Signal"):             jen.Id(pascalName + "Signal"),
			jen.Id("ActionProto"):        jen.Op("&").Id(msgName).Values(),
			jen.Id("WorkflowIDFunc"):     jen.Id(msgName + "WorkflowID"),
			jen.Id("TenantIDFunc"):       jen.Id(msgName + "TenantID"),
			jen.Id("EntityIDsFunc"):      jen.Id(msgName + "EntityIDs"),
			jen.Id("WorkflowIDFromArgs"): jen.Id(pascalName + "WorkflowIDFromArgs"),
		})),
	)
	code.Line()
}

func (m *Module) generateWorkflowIDArgs(msg pgs.Message, fieldNames []string) []jen.Code {
	args := make([]jen.Code, 0, len(fieldNames)+1)
	// First argument is the format string (already added by caller)

	for _, fieldName := range fieldNames {
		field := m.findField(msg, fieldName)
		goFieldName := field.Name().UpperCamelCase().String()
		args = append(args, jen.Id("a").Dot("Get"+goFieldName).Call())
	}

	return args
}

func (m *Module) generateInit(code *jen.File, messages []pgs.Message) {
	if len(messages) == 0 {
		return
	}

	var stmts []jen.Code
	for _, msg := range messages {
		// Get action annotation
		opts := msg.Descriptor().GetOptions()
		ext := proto.GetExtension(opts, actionqueuepb.E_Action).(*actionqueuepb.MessageOptions)
		pascalName := toPascalCase(ext.Name)

		stmts = append(stmts,
			jen.Qual("github.com/jirwin/protoc-gen-actionqueue/pkg/actionqueue", "Register").Call(
				jen.Id(pascalName+"Definition").Call(),
			),
		)
	}

	code.Func().Id("init").Params().Block(stmts...)
}

func (m *Module) findField(msg pgs.Message, fieldName string) pgs.Field {
	for _, field := range msg.Fields() {
		if field.Name().String() == fieldName {
			return field
		}
	}
	return nil
}

// toPascalCase converts a kebab-case or snake_case string to PascalCase
// e.g., "my-entity-queue" -> "MyEntityQueue"
func toPascalCase(s string) string {
	// Replace hyphens with spaces for word separation
	s = strings.ReplaceAll(s, "-", " ")
	s = strings.ReplaceAll(s, "_", " ")

	words := strings.Fields(s)
	for i, word := range words {
		if len(word) > 0 {
			words[i] = strings.ToUpper(string(word[0])) + strings.ToLower(word[1:])
		}
	}

	return strings.Join(words, "")
}
