// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: actionqueue/v1/options.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageOptions marks a message as an action queue action proto and configures generation.
type MessageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique workflow name (e.g., "my-entity-queue")
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// signal is the signal name to wake the workflow (e.g., "signal:start:my-entity-queue")
	Signal string `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	// workflow_id_fields are field names to compose the workflow ID.
	// Example: ["tenant_id", "entity_id"] -> "my-queue:{tenant_id}:{entity_id}"
	WorkflowIdFields []string `protobuf:"bytes,3,rep,name=workflow_id_fields,json=workflowIdFields,proto3" json:"workflow_id_fields,omitempty"`
	// tenant_id_field is the field name for tenant extraction (default: "tenant_id")
	TenantIdField string `protobuf:"bytes,4,opt,name=tenant_id_field,json=tenantIdField,proto3" json:"tenant_id_field,omitempty"`
	// id_field is the per-action unique ID field name (default: "id")
	IdField       string `protobuf:"bytes,5,opt,name=id_field,json=idField,proto3" json:"id_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_actionqueue_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_actionqueue_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_actionqueue_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *MessageOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MessageOptions) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *MessageOptions) GetWorkflowIdFields() []string {
	if x != nil {
		return x.WorkflowIdFields
	}
	return nil
}

func (x *MessageOptions) GetTenantIdField() string {
	if x != nil {
		return x.TenantIdField
	}
	return ""
}

func (x *MessageOptions) GetIdField() string {
	if x != nil {
		return x.IdField
	}
	return ""
}

var file_actionqueue_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         7100,
		Name:          "actionqueue.v1.action",
		Tag:           "bytes,7100,opt,name=action",
		Filename:      "actionqueue/v1/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional actionqueue.v1.MessageOptions action = 7100;
	E_Action = &file_actionqueue_v1_options_proto_extTypes[0]
)

var File_actionqueue_v1_options_proto protoreflect.FileDescriptor

const file_actionqueue_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x1cactionqueue/v1/options.proto\x12\x0eactionqueue.v1\x1a google/protobuf/descriptor.proto\"\xad\x01\n" +
	"\x0eMessageOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\x12,\n" +
	"\x12workflow_id_fields\x18\x03 \x03(\tR\x10workflowIdFields\x12&\n" +
	"\x0ftenant_id_field\x18\x04 \x01(\tR\rtenantIdField\x12\x19\n" +
	"\bid_field\x18\x05 \x01(\tR\aidField:X\n" +
	"\x06action\x12\x1f.google.protobuf.MessageOptions\x18\xbc7 \x01(\v2\x1e.actionqueue.v1.MessageOptionsR\x06actionB9Z7github.com/jirwin/protoc-gen-actionqueue/actionqueue/v1b\x06proto3"

var (
	file_actionqueue_v1_options_proto_rawDescOnce sync.Once
	file_actionqueue_v1_options_proto_rawDescData []byte
)

func file_actionqueue_v1_options_proto_rawDescGZIP() []byte {
	file_actionqueue_v1_options_proto_rawDescOnce.Do(func() {
		file_actionqueue_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actionqueue_v1_options_proto_rawDesc), len(file_actionqueue_v1_options_proto_rawDesc)))
	})
	return file_actionqueue_v1_options_proto_rawDescData
}

var file_actionqueue_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_actionqueue_v1_options_proto_goTypes = []any{
	(*MessageOptions)(nil),              // 0: actionqueue.v1.MessageOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_actionqueue_v1_options_proto_depIdxs = []int32{
	1, // 0: actionqueue.v1.action:extendee -> google.protobuf.MessageOptions
	0, // 1: actionqueue.v1.action:type_name -> actionqueue.v1.MessageOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_actionqueue_v1_options_proto_init() }
func file_actionqueue_v1_options_proto_init() {
	if File_actionqueue_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actionqueue_v1_options_proto_rawDesc), len(file_actionqueue_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_actionqueue_v1_options_proto_goTypes,
		DependencyIndexes: file_actionqueue_v1_options_proto_depIdxs,
		MessageInfos:      file_actionqueue_v1_options_proto_msgTypes,
		ExtensionInfos:    file_actionqueue_v1_options_proto_extTypes,
	}.Build()
	File_actionqueue_v1_options_proto = out.File
	file_actionqueue_v1_options_proto_goTypes = nil
	file_actionqueue_v1_options_proto_depIdxs = nil
}
